### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by etosch** [lspector/taggp#12]
Add system-wide tests in addition to unit test for new features.

Unit tests can be attached to functions in metadata (I'm currently having difficulty pulling this off).

Where to put larger system tests?

**Comment by kephale** [comment]
If they go into taggp/test then they should play nicely with lein test. Note that lein test works with Midje as well. There is also a lein-cuke plugin, but I don't think cucumber is popular enough in the Clojure community for this to be a worthwhile investment yet.

**Comment by etosch** [comment]
wont fix
